#!/usr/bin/env php
<?php
// paris-generator
require 'vendor/autoload.php';

use DavidePastore\ParisModelGenerator\ParisGeneratorCommand;

use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new ParisGeneratorCommand);
$application->run();